<?php
/*
 * Create custom post type
 * */
add_action('init', 'init_post_types');
function init_post_types()
{
    register_post_type('courses', array(
        'label' => null,
        'labels' => array(
            'name' => 'Авторські проєкти',
            'singular_name' => 'Проєкт',
            'add_new' => 'Додати проєкт',
            'add_new_item' => 'Додавання нового проєкту',
            'edit_item' => 'Редагування проєкту',
            'new_item' => 'Новий проєкт',
            'view_item' => 'Перегляд проєкту',
            'search_items' => 'Пошук проєктів',
            'not_found' => 'Не знайдено проєктів',
            'not_found_in_trash' => 'В кошику не знайдено проєктів',
            'parent_item_colon' => '',
            'menu_name' => 'Авторські проєкти',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => true,
        'supports' => array('title', 'thumbnail', 'editor', 'excerpt', 'custom-fields'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => true,
        'menu_icon' => 'dashicons-book',
        'rewrite' => array(
            'slug' => 'projects',
            'with_front' => false 
        ),
    ));

    register_post_type('interesting', array(
        'label' => null,
        'labels' => array(
            'name' => 'Цікавинки',
            'singular_name' => 'Цікавинка',
            'add_new' => 'Додати цікавинку',
            'add_new_item' => 'Додавання нової цікавинки',
            'edit_item' => 'Редагування цікавинки',
            'new_item' => 'Нова цікавинка',
            'view_item' => 'Перегляд цікавинки',
            'search_items' => 'Пошук цікавинок',
            'not_found' => 'Не знайдено цікавинок',
            'not_found_in_trash' => 'В кошику не знайдено цікавинок',
            'parent_item_colon' => '',
            'menu_name' => 'Цікавинки',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'editor', 'excerpt', 'custom-fields'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => true,
        'menu_icon' => 'dashicons-smiley',));


    register_post_type('updates', array(
        'label' => null,
        'labels' => array(
            'name' => 'Оновлення',
            'singular_name' => 'Оновлення',
            'add_new' => 'Додати оновлення',
            'add_new_item' => 'Додати оновлення',
            'edit_item' => 'Редагування оновлення',
            'new_item' => 'Нове оновлення',
            'view_item' => 'Перегляд оновлення',
            'search_items' => 'Пошук оновлення',
            'not_found' => 'Не знайдено оновлення',
            'not_found_in_trash' => 'В кошику не знайдено оновлень',
            'parent_item_colon' => '',
            'menu_name' => 'Оновлення річного курсу',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => true,
        'supports' => array('title', 'thumbnail', 'custom-fields'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => true,
        'menu_icon' => 'dashicons-format-audio',


    ));
    register_post_type('videos', array(
        'label' => null,
        'labels' => array(
            'name' => 'Відеоуроки ',
            'singular_name' => 'Відеоурок',
            'add_new' => 'Додати відеоурок',
            'add_new_item' => 'Додати відеоурок',
            'edit_item' => 'Редагування відеоурок',
            'new_item' => 'Новий відеоурок',
            'view_item' => 'Перегляд відеоуроку',
            'search_items' => 'Пошук відеоуроку',
            'not_found' => 'Не знайдено відеоуроку',
            'not_found_in_trash' => 'В кошику не знайдено відеоуроків',
            'parent_item_colon' => '',
            'menu_name' => 'Відеоуроки',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'custom-fields'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => true,
        'menu_icon' => 'dashicons-format-video',


    ));
}
