<?php
/*
 * Create custom post type
 * */
add_action('init', 'init_post_types');
function init_post_types()
{
    register_post_type('courses', array(
        'label' => null,
        'labels' => array(
            'name' => 'Авторські проєкти',
            'singular_name' => 'Проєкт',
            'add_new' => 'Додати проєкт',
            'add_new_item' => 'Додавання нового проєкту',
            'edit_item' => 'Редагування проєкту',
            'new_item' => 'Новий проєкт',
            'view_item' => 'Перегляд проєкту',
            'search_items' => 'Пошук проєктів',
            'not_found' => 'Не знайдено проєктів',
            'not_found_in_trash' => 'В кошику не знайдено проєктів',
            'parent_item_colon' => '',
            'menu_name' => 'Авторські проєкти',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => true,
        'supports' => array('title', 'thumbnail', 'editor', 'excerpt', 'custom-fields'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => true,
        'menu_icon' => 'dashicons-book',
        'rewrite' => array(
            'slug' => 'projects',
            'with_front' => false
        ),
    ));

    register_post_type('interesting', array(
        'label' => null,
        'labels' => array(
            'name' => 'Цікавинки',
            'singular_name' => 'Цікавинка',
            'add_new' => 'Додати цікавинку',
            'add_new_item' => 'Додавання нової цікавинки',
            'edit_item' => 'Редагування цікавинки',
            'new_item' => 'Нова цікавинка',
            'view_item' => 'Перегляд цікавинки',
            'search_items' => 'Пошук цікавинок',
            'not_found' => 'Не знайдено цікавинок',
            'not_found_in_trash' => 'В кошику не знайдено цікавинок',
            'parent_item_colon' => '',
            'menu_name' => 'Цікавинки',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'editor', 'excerpt', 'custom-fields'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => true,
        'menu_icon' => 'dashicons-smiley',
    ));

    register_post_type('product', array(
        'label' => 'Товари',
        'labels' => array(
            'name'               => 'Товари',
            'singular_name'      => 'Товар',
            'add_new'            => 'Додати Товар',
            'add_new_item'       => 'Додати новий Товар',
            'edit_item'          => 'Редагувати Товар',
            'new_item'           => 'Новий Товар',
            'view_item'          => 'Переглянути Товар',
            'search_items'       => 'Пошук Товарів',
            'not_found'          => 'Товарів не знайдено',
            'not_found_in_trash' => 'В кошику не знайдено Товарів',
            'menu_name'          => 'Товари',
        ),
        'public'            => false,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui'           => true,
        'show_in_menu'      => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => false,
        'show_in_rest'      => true,
        'rest_base'         => 'product',
        'menu_position'     => 5,
        'menu_icon'         => 'dashicons-products',
        'hierarchical'      => false,
        'supports'          => array('title'),
        'taxonomies'        => array('product_category'),
        'has_archive'       => false,
        'rewrite'           => array(
            'slug'       => 'product',
            'with_front' => false,
            'pages'      => true,
        ),
        'query_var' => false,
    ));

    register_post_type('faq', array(
        'label' => 'Часті питання',
        'labels' => array(
            'name'               => 'Часті питання',
            'singular_name'      => 'Питання',
            'add_new'            => 'Додати Питання',
            'add_new_item'       => 'Додати нове Питання',
            'edit_item'          => 'Редагувати Питання',
            'new_item'           => 'Нове Питання',
            'view_item'          => 'Переглянути Питання',
            'search_items'       => 'Пошук Питань',
            'not_found'          => 'Питань не знайдено',
            'not_found_in_trash' => 'В кошику не знайдено Питань',
            'menu_name'          => 'FAQ',
        ),
        'public'             => true,
        'publicly_queryable' => false,
        'exclude_from_search' => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'show_in_admin_bar'  => true,
        'show_in_nav_menus'  => false,
        'show_in_rest'       => true,
        'rest_base'          => 'faq',
        'menu_position'      => 9,
        'menu_icon'          => 'dashicons-editor-help',
        'hierarchical'       => false,
        'supports'           => array('title', 'editor'),
        'taxonomies'         => array('faq_category'),
        'has_archive'        => false,
        'rewrite'            => false,
        'query_var'          => false,
    ));

    register_post_type('review', array(
        'label' => 'Відгуки',
        'labels' => array(
            'name'               => 'Відгуки',
            'singular_name'      => 'Відгук',
            'add_new'            => 'Додати Відгук',
            'add_new_item'       => 'Додати новий Відгук',
            'edit_item'          => 'Редагувати Відгук',
            'new_item'           => 'Новий Відгук',
            'view_item'          => 'Переглянути Відгук',
            'search_items'       => 'Пошук Відгуків',
            'not_found'          => 'Відгуків не знайдено',
            'not_found_in_trash' => 'В кошику не знайдено Відгуків',
            'menu_name'          => 'Відгуки',
        ),
        'public'             => true,
        'publicly_queryable' => false,
        'exclude_from_search' => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'show_in_admin_bar'  => true,
        'show_in_nav_menus'  => false,
        'show_in_rest'       => true,
        'rest_base'          => 'review',
        'menu_position'      => 10,
        'menu_icon'          => 'dashicons-format-quote',
        'hierarchical'       => false,
        'supports'           => array('title', 'editor', 'thumbnail'),
        'taxonomies'         => array('review_category'),
        'has_archive'        => false,
        'rewrite'            => false,
        'query_var'          => false,
    ));
}
