<?php
add_action('init', 'init_taxonomies');
function init_taxonomies()
{
    register_taxonomy('product_category', array('product'), array(
        'label' => 'Категорії продуктів',
        'labels' => array(
            'name'                       => 'Категорії продуктів',
            'singular_name'              => 'Категорія продукту',
            'add_new_item'               => 'Додати нову Категорію',
            'edit_item'                  => 'Редагувати Категорію',
            'new_item_name'              => 'Назва нової Категорії',
            'search_items'               => 'Пошук Категорій',
            'not_found'                  => 'Категорій не знайдено',
            'menu_name'                  => 'Категорії',
            'back_to_items'              => '← Повернутися до Категорій',
        ),
        'description'        => 'Категорія для Продукту',
        'public'             => true,
        'publicly_queryable' => true,
        'hierarchical'       => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'show_in_nav_menus'  => false,
        'show_in_rest'       => true,
        'rest_base'          => 'product-category',
        'show_admin_column'  => true,
        'show_in_quick_edit' => true,
        'show_tagcloud'      => false,
        'meta_box_cb'        => 'post_categories_meta_box',
        'rewrite'            => array(
            'slug'       => 'product-category',
            'with_front' => true,
            'pages'      => true,
        ),
        'query_var' => true,
    ));

    register_taxonomy('product_tag', array('product'), array(
        'label' => 'Теги продуктів',
        'labels' => array(
            'name'                       => 'Теги продуктів',
            'singular_name'              => 'Тег продукту',
            'add_new_item'               => 'Додати новий Тег',
            'edit_item'                  => 'Редагувати Тег',
            'new_item_name'              => 'Назва нового Тегу',
            'search_items'               => 'Пошук Тегів',
            'not_found'                  => 'Тегів не знайдено',
            'menu_name'                  => 'Теги',
            'back_to_items'              => '← Повернутися до Тегів',
        ),
        'description'        => 'Тег для Продукту',
        'public'             => true,
        'publicly_queryable' => true,
        'hierarchical'       => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'show_in_nav_menus'  => false,
        'show_in_rest'       => true,
        'rest_base'          => 'product-tag',
        'show_admin_column'  => true,
        'show_in_quick_edit' => true,
        'show_tagcloud'      => false,
        'meta_box_cb'        => 'post_categories_meta_box',
        'rewrite'            => array(
            'slug'       => 'product-tag',
            'with_front' => true,
            'pages'      => true,
        ),
        'query_var' => true,
    ));

    register_taxonomy('faq_category', array('faq'), array(
        'label' => 'Категорії питань',
        'labels' => array(
            'name'                       => 'Категорії питань',
            'singular_name'              => 'Категорія питання',
            'add_new_item'               => 'Додати нову Категорію',
            'edit_item'                  => 'Редагувати Категорію',
            'new_item_name'              => 'Назва нової Категорії',
            'search_items'               => 'Пошук Категорій',
            'not_found'                  => 'Категорій не знайдено',
            'menu_name'                  => 'Категорії',
            'back_to_items'              => '← Повернутися до Категорій',
        ),
        'description'        => 'Категорія для FAQ',
        'public'             => false,
        'publicly_queryable' => false,
        'hierarchical'       => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'show_in_nav_menus'  => false,
        'show_in_rest'       => true,
        'rest_base'          => 'faq-category',
        'show_admin_column'  => true,
        'show_in_quick_edit' => true,
        'show_tagcloud'      => false,
        'meta_box_cb'        => 'post_categories_meta_box',
        'rewrite'            => false,
        'query_var'          => false,
    ));

    register_taxonomy('review_category', array('review'), array(
        'label' => 'Категорії відгуків',
        'labels' => array(
            'name'                       => 'Категорії відгуків',
            'singular_name'              => 'Категорія відгуку',
            'add_new_item'               => 'Додати нову Категорію',
            'edit_item'                  => 'Редагувати Категорію',
            'new_item_name'              => 'Назва нової Категорії',
            'search_items'               => 'Пошук Категорій',
            'not_found'                  => 'Категорій не знайдено',
            'menu_name'                  => 'Категорії',
            'back_to_items'              => '← Повернутися до Категорій',
        ),
        'description'        => 'Категорія для Відгуку',
        'public'             => false,
        'publicly_queryable' => false,
        'hierarchical'       => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'show_in_nav_menus'  => false,
        'show_in_rest'       => true,
        'rest_base'          => 'review-category',
        'show_admin_column'  => true,
        'show_in_quick_edit' => true,
        'show_tagcloud'      => false,
        'meta_box_cb'        => 'post_categories_meta_box',
        'rewrite'            => false,
        'query_var'          => false,
    ));
}
